# Essential types only
- id: new-feature
  match: "src/**/*.{ts,tsx}"
  type: feat
  reason: "New feature implementation"
  
- id: bug-fix
  match_ast: "implementation_changed"
  type: fix
  reason: "Bug fix or implementation change"
  
- id: documentation
  match: "**/*.{md,txt,doc,docx}"
  type: docs
  reason: "Documentation change"
  
- id: test-file
  match: "**/*.{spec,test}.{ts,tsx,js,jsx}"
  type: test
  reason: "Test file changes"
  
- id: code-refactor
  match_ast: "rename_symbol || move_declaration || extract_function"
  type: refactor
  reason: "Code refactoring"
  
# Breaking changes are detected by severity in rules-engine.ts
