name: PR Quality Check

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
        
    - name: Check PR Title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
        requireScope: false
        
    - name: PR Size Check
      uses: actions/github-script@v6
      with:
        script: |
          const { data: files } = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });
          
          const changes = files.reduce((acc, file) => acc + file.changes, 0);
          const filesChanged = files.length;
          
          let sizeLabel = '';
          let sizeMark = '✓';
          let sizeComment = 'OK';
          
          if (changes > 1000) {
            sizeLabel = 'size:xl';
            sizeMark = '⚠️';
            sizeComment = 'Consider breaking this PR into smaller ones';
          } else if (changes > 500) {
            sizeLabel = 'size:l';
            sizeMark = '⚠️';
            sizeComment = 'Large PR, careful review needed';
          } else if (changes > 200) {
            sizeLabel = 'size:m';
          } else if (changes > 50) {
            sizeLabel = 'size:s';
          } else {
            sizeLabel = 'size:xs';
          }
          
          await github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: [sizeLabel]
          });
          
          const comment = `## PR Size Check
          
          ${sizeMark} Changes: ${changes} lines
          ${sizeMark} Files: ${filesChanged} files
          
          **Size**: ${sizeLabel.replace('size:', '')}
          
          ${sizeComment}`;
          
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
          
    - name: Lint Check
      id: lint
      run: npm run lint
      continue-on-error: true
      
    - name: Test Coverage Check
      id: test
      run: npm run test:coverage
      continue-on-error: true
      
    - name: Comment PR
      uses: actions/github-script@v6
      with:
        script: |
          const lintStatus = '${{ steps.lint.outcome }}' === 'success' ? '✅ Passed' : '❌ Failed';
          const testStatus = '${{ steps.test.outcome }}' === 'success' ? '✅ Passed' : '❌ Failed';
          
          const comment = `## Quality Check Results
          
          | Check | Status |
          | ----- | ------ |
          | Lint | ${lintStatus} |
          | Tests | ${testStatus} |
          
          *This automated check helps maintain code quality standards. Please fix any issues before requesting a review.*`;
          
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
